### ISSUE TITLE
Link in wiki leads to blank page

### ISSUE THREAD

**Issue by brucejackson** [jphfilm/rpi-film-capture#2]
Hi Joe,

I found your project because of the recent article you wrote for IEEE Spectrum.  It really caught my eye as my brother and I found a bunch of family films that we would like to preserve.  I read through the wiki you provided it is informative and has inspired me to start looking at a DIY solution to preserving the movies.  

On the page: https://github.com/jphfilm/rpi-film-capture/wiki/Parts-Selection, if I click on "discussion" in the "Raspberry Pi Camera and extension cable" bullet, I get an empty page at this URL (https://raw.githubusercontent.com/wiki/jphfilm/rpi-film-capture/Camera-and-Optics.md)

I was wondering if this is something you haven't written or if it is an error in the link.

Thanks for sharing all your effort and experience!
Bruce.

**Comment by jphfilm** [comment]
Bruce,
It's a page I neglected to write initially; the project and wiki existed in
obscurity for a while after my initial upload so I had it on my "one of
these days I should get to that" todo list, but it's got much more traffic
since the Spectrum article appeared so I should definitely write that part
now.  I'll get something basic up there today and try to add more early
next week.
I'm delighted that people might actually be using it and trying something
like this themselves.  If you have any questions or suggestions as you work
through this stuff, please don't hesitate to contact me at
jopher91@gmail.com

**Comment by markhern** [comment]
Joe, O'Reilly Media is linking to your Spectrum article and that is how I found it. Kudos on the phenomenal work, and the results are beautiful as you described. Thank you for releasing this project to the world so that others can benefit. It's quite nice that you have a Christmas related family video as an example at this time of year. Christmas memories make these type of projects all the more important. Thanks again.

**Comment by jphfilm** [comment]
@markhern, Thanks!  Could you guide me to the O'Reilly link (for ego-boosting purposes)?  I couldn't find it in a quick search.

**Comment by djsinned** [comment]
Hi Joe, the link I believe is this one.
http://spectrum.ieee.org/geek-life/hands-on/how-to-convert-old-film-reels-with-a-raspberry-pi

Cheers
Dennis

**Comment by jphfilm** [comment]
Oh, THAT I knew of! I thought Oreilly.com might have something, per
markhern. Thanks for replying though.

**Comment by markhern** [comment]
Joe, the link was from the O'Reilly Programming newsletter which I signed up to receive in my email. It doesn't appear to be a regular part of the OR website. Hopefully, this link below opens for you:
http://post.oreilly.com/form/oreilly/viewhtml/9z1z2kqe0ntht906aebhpeiltadurgv9sn9l4l4p68o?imm_mid=0eb7bb&cmp=em-prog-na-na-newsltr_20161210

**Comment by jphfilm** [comment]
Thanks! Good to know.
